# Generated by Django 5.0.1 on 2024-03-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidateanswer',
            table='CandidateAnswers',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='Exam',
        ),
        migrations.AlterModelTable(
            name='ques',
            table='Ques',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='SubCategory',
        ),
    ]
