# Generated by Django 5.0.1 on 2024-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_candidateanswer_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswer',
            name='is_correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
