# Generated by Django 5.0.1 on 2024-03-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_candidateanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
