# Generated by Django 5.0.1 on 2024-03-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_scores'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scores',
            table='Scores',
        ),
    ]
