# Generated by Django 5.0.1 on 2024-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_scores_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
