# Generated by Django 5.0.1 on 2024-02-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
    ]
