# Generated by Django 5.0.1 on 2024-02-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_table_alter_quiz_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
    ]
