# Generated by Django 5.0.1 on 2024-02-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_questions_question_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_At',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionOptions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_At',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_At',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_At',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
    ]
