# Generated by Django 5.0.1 on 2024-02-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_useranswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='samp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
