# Generated by Django 5.0.1 on 2024-02-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_useranswers_samp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='samp',
        ),
    ]
